import Sidebar from '@/components/Sidebar'
import './globals.css'

export const metadata = {
  title: 'Amazon Web Scraper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7FBFF] h-screen">
        {/* Sidebar */}
        <Sidebar />

        <main className="p-10 max-w-7xl">
          {/* Header */}
          {children}
        </main>
      </body>
    </html>
  )
}
